services:
  client:
    container_name: steamwallet-frontend
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 5174:3000
